import { Component, Input, OnChanges, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Api, Assessment, Node } from './api';
import { ActionState, FieldComponent, StatusComponent } from './shared';
@Component({selector:'app-assessments',standalone:true,imports:[ReactiveFormsModule,FieldComponent,StatusComponent],template:`
<div class="section-heading"><div><p class="eyebrow">From questions to evidence</p><h2>Assessments</h2></div><button class="secondary" (click)="load()" [disabled]="state.busy() || !classroomId">Refresh assessments</button></div><p>Author an objective question or open an assessment to submit your work. Published assessments are immutable; each student can submit once.</p>
<div class="split"><section class="panel"><h3>Classroom assessments</h3><p class="caption">Up to 100 most recent assessments</p>@for(item of assessments();track item.id){<article class="record"><strong>{{item.title}}</strong><button class="secondary" (click)="open(item.id)" [disabled]="state.busy()">Open assessment</button></article>}@empty{<p class="empty">{{classroomId?'No assessments yet. Create one using a curriculum skill.':'Select a classroom to continue.'}}</p>}
@if(selected();as assessment){<div class="separated"><h3>{{assessment.title}}</h3><form novalidate [formGroup]="answers" (ngSubmit)="submit()">@for(question of assessment.questions;track question.id){<app-field [controlId]="'answer-'+question.id" [label]="question.prompt" [invalid]="!!answers.get(question.id!)?.touched && !!answers.get(question.id!)?.invalid">@if(question.type==='numerical'){<input [id]="'answer-'+question.id" [formControlName]="question.id!" inputmode="decimal" [attr.aria-describedby]="'answer-'+question.id+'-help'">}@else{<select [id]="'answer-'+question.id" [formControlName]="question.id!"><option value="">Choose an answer</option>@for(option of question.options;track option){<option [value]="option">{{option}}</option>}</select>}</app-field>}
@if(api.profile()?.role==='student'){<p class="caption">Submission is final. Check your answers before submitting.</p><button [disabled]="state.busy() || submitted()">{{submitted()?'Submitted':'Submit answers'}}</button>}@else{<p class="caption">Teacher preview. Students see the question without its answer key.</p>}<button type="reset" class="secondary clear-form" [disabled]="state.busy()">Clear form</button></form></div>}</section>
@if(api.profile()?.role==='teacher'){<section class="panel"><h3>Create an assessment</h3><p class="caption">The foundation editor authors one question. The API supports up to 50 questions.</p><form novalidate [formGroup]="form" (ngSubmit)="create()">
<app-field controlId="assessment-title" label="Assessment title" [invalid]="form.controls.title.touched && form.controls.title.invalid"><input id="assessment-title" formControlName="title" maxlength="160" aria-describedby="assessment-title-help"></app-field>
<app-field controlId="question-prompt" label="Question" [invalid]="form.controls.prompt.touched && form.controls.prompt.invalid"><textarea id="question-prompt" formControlName="prompt" rows="4" maxlength="2000" style="resize: none" aria-describedby="question-prompt-help"></textarea></app-field>
<app-field controlId="question-skill" label="Curriculum skill" [invalid]="form.controls.skill_id.touched && form.controls.skill_id.invalid"><select id="question-skill" formControlName="skill_id"><option value="">Choose a skill</option>@for(skill of skills();track skill.id){<option [value]="skill.id">{{skill.name}}</option>}</select></app-field>
<app-field controlId="question-type" label="Question type"><select id="question-type" formControlName="type"><option value="numerical">Numerical</option><option value="multiple_choice">Multiple choice</option></select></app-field>
@if(form.controls.type.value==='multiple_choice'){<app-field controlId="question-options" label="Answer options" hint="One option per line; 2–8 unique options."><textarea id="question-options" formControlName="options" rows="4" style="resize: none" aria-describedby="question-options-help"></textarea></app-field>}
<app-field controlId="question-key" label="Correct answer" hint="For multiple choice, use the exact option text." [invalid]="form.controls.answer.touched && form.controls.answer.invalid"><input id="question-key" formControlName="answer" aria-describedby="question-key-help"></app-field>
@if(form.controls.type.value==='numerical'){<app-field controlId="question-tolerance" label="Numerical tolerance" hint="Use 0 for an exact match."><input id="question-tolerance" formControlName="tolerance" inputmode="decimal" aria-describedby="question-tolerance-help"></app-field>}
<button [disabled]="state.busy() || !classroomId">Create assessment</button><button type="reset" class="secondary clear-form" [disabled]="state.busy()">Clear form</button></form></section>}</div><app-status [state]="state"/>`})
export class AssessmentsComponent implements OnChanges {
  readonly api=inject(Api);readonly state=new ActionState();@Input() classroomId='';readonly assessments=signal<Pick<Assessment,'id'|'title'>[]>([]);readonly skills=signal<Node[]>([]);readonly selected=signal<Assessment|null>(null);readonly submitted=signal(false);answers=new FormGroup<Record<string,FormControl<string>>>({});
  readonly form=new FormGroup({title:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.maxLength(160)]}),prompt:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.maxLength(2000)]}),skill_id:new FormControl('',{nonNullable:true,validators:[Validators.required]}),type:new FormControl<'numerical'|'multiple_choice'>('numerical',{nonNullable:true}),options:new FormControl('',{nonNullable:true}),answer:new FormControl('',{nonNullable:true,validators:[Validators.required]}),tolerance:new FormControl('0',{nonNullable:true})});
  ngOnChanges():void{this.selected.set(null);this.assessments.set([]);this.load();}
  load():void{if(!this.classroomId)return;void this.state.run(async()=>{this.assessments.set(await this.api.assessments(this.classroomId));this.skills.set((await this.api.nodes()).filter(n=>n.kind==='skill'));});}
  create():void{if(!this.state.validate(this.form))return;void this.state.run(async()=>{const v=this.form.getRawValue();await this.api.request('assessment','/assessments','POST',{classroom_id:this.classroomId,title:v.title,questions:[{prompt:v.prompt,skill_id:v.skill_id,type:v.type,answer:v.answer,options:v.type==='multiple_choice'?v.options.split('\n').map(s=>s.trim()).filter(Boolean):[],tolerance:v.type==='numerical'?v.tolerance:''}]});this.form.reset({type:'numerical',tolerance:'0'});this.assessments.set(await this.api.assessments(this.classroomId));},'Assessment created.');}
  open(id:string):void{if(this.answers.dirty){this.state.error.set('Submit your current answers before opening another assessment.');return;}void this.state.run(async()=>{const assessment=await this.api.request<Assessment>('assessment',`/assessments/${id}`);this.answers=new FormGroup(Object.fromEntries(assessment.questions.map(q=>[q.id!,new FormControl('',{nonNullable:true,validators:[Validators.required]})])));this.selected.set(assessment);this.submitted.set(false);});}
  submit():void{if(!this.state.validate(this.answers))return;void this.state.run(async()=>{await this.api.request('assessment',`/assessments/${this.selected()?.id}/submissions`,'POST',{answers:this.answers.getRawValue()});this.answers.markAsPristine();this.submitted.set(true);},'Answers submitted. Your teacher will review the grade.');}
}


