import { Component, Input, OnChanges, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Api, DocumentRecord } from './api';
import { ActionState, FieldComponent, StatusComponent } from './shared';
@Component({selector:'app-materials',standalone:true,imports:[ReactiveFormsModule,FieldComponent,StatusComponent],template:`
<div class="section-heading"><div><p class="eyebrow">A shared source of learning</p><h2>Teaching materials</h2></div><button class="secondary" (click)="load()" [disabled]="state.busy() || !classroomId">Refresh materials</button></div><p>Upload original teaching documents. Text files are extracted into traceable chunks; PDF extraction and AI indexing are not available yet.</p>
<div class="split"><section class="panel"><h3>Classroom library</h3><p class="caption">Up to 100 most recent documents</p>@for(doc of documents();track doc.id){<article class="record"><strong>{{doc.title}}</strong><span class="badge">{{doc.status==='extracted'?'Text extracted · not indexed':'PDF extraction unavailable'}}</span><small>Revision {{doc.revision}} · {{doc.mime_type}}</small></article>}@empty{<p class="empty">{{classroomId?'No documents in this classroom. Upload a teaching resource to begin.':'Select a classroom to view its materials.'}}</p>}</section>
@if(api.profile()?.role==='teacher'){<section class="panel"><h3>Upload a document</h3><form novalidate [formGroup]="form" (ngSubmit)="upload()"><app-field controlId="document-title" label="Document title" [invalid]="form.controls.title.touched && form.controls.title.invalid"><input id="document-title" formControlName="title" maxlength="160" aria-describedby="document-title-help" [attr.aria-invalid]="form.controls.title.touched && form.controls.title.invalid"></app-field><app-field controlId="document-file" label="Educational file" hint="UTF-8 .txt or PDF, up to 5 MiB."><input id="document-file" type="file" accept=".txt,.pdf" (change)="selectFile($event)" aria-describedby="document-file-help"></app-field>@if(file()){<p>{{file()?.name}}</p>}<button [disabled]="state.busy() || !classroomId">Upload document</button><button type="reset" class="secondary clear-form" (click)="file.set(null)" [disabled]="state.busy()">Clear form</button></form></section>}</div><app-status [state]="state"/>`})
export class MaterialsComponent implements OnChanges {
  readonly api=inject(Api);readonly state=new ActionState();readonly documents=signal<DocumentRecord[]>([]);readonly file=signal<File|null>(null);@Input() classroomId='';private revision=0;
  readonly form=new FormGroup({title:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.maxLength(160),Validators.pattern(/\S/)]})});
  ngOnChanges():void{this.documents.set([]);this.load();}load():void{const id=this.classroomId,revision=++this.revision;if(!id)return;void this.state.run(async()=>{const docs=await this.api.documents(id);if(revision===this.revision)this.documents.set(docs);});}
  selectFile(event:Event):void{const file=(event.target as HTMLInputElement).files?.[0]||null;if(file&&(file.size===0||file.size>5*1024*1024||!(/\.(txt|pdf)$/i).test(file.name))){this.state.error.set('Choose a nonempty .txt or PDF file no larger than 5 MiB.');this.file.set(null);return;}this.file.set(file);this.form.markAsDirty();}
  upload():void{if(!this.state.validate(this.form))return;const file=this.file();if(!file){this.state.error.set('Choose a file to upload.');return;}void this.state.run(async()=>{await this.api.request('content',`/documents?classroom_id=${this.classroomId}&title=${encodeURIComponent(this.form.controls.title.value)}`,'POST',file,file.name.toLowerCase().endsWith('.pdf')?'application/pdf':'text/plain');this.form.reset();this.file.set(null);this.documents.set(await this.api.documents(this.classroomId));},'Document uploaded. AI indexing remains unavailable.');}
}


