import { Component, ElementRef, Input, OnChanges, ViewChild, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Api, Evaluation } from './api';
import { ActionState, FieldComponent, StatusComponent } from './shared';
@Component({selector:'app-review',standalone:true,imports:[ReactiveFormsModule,FieldComponent,StatusComponent],template:`
<div class="section-heading"><div><p class="eyebrow">A teacher makes the final decision</p><h2>Grading review</h2></div><button class="secondary" (click)="load()" [disabled]="state.busy() || !classroomId">Refresh grades</button></div><p>Deterministic scores are drafts until you review and finalize them. Only finalized evidence reaches the performance dashboard.</p><section class="panel"><p class="caption">Up to 100 most recent evaluations</p>@for(grade of grades();track grade.id){<article class="grade"><div><span class="badge">{{grade.status}}</span><h3>Student <span class="identifier">{{grade.student_id}}</span></h3></div><div class="evidence-list">@for(evidence of grade.evidence;track evidence.question_id){<p><strong>{{evidence.awarded}} / {{evidence.possible}}</strong> · Question <span class="identifier">{{evidence.question_id}}</span></p>}</div>@if(grade.status==='draft'){<button (click)="review(grade)" [disabled]="state.busy()">Review grade</button>}</article>}@empty{<p class="empty">No grading evidence yet. Student submissions will appear here after processing. Refresh to check again.</p>}</section>@if(!selected()){<app-status [state]="state"/>}
<dialog #dialog aria-labelledby="review-title" (close)="close()"><h2 id="review-title">Finalize this grade?</h2><p>Finalization publishes this student's scores to their performance record. This grade cannot be changed in this milestone.</p><form novalidate [formGroup]="form" (ngSubmit)="finalize()"><app-field controlId="review-reason" label="Review notes" [invalid]="form.controls.reason.touched && form.controls.reason.invalid"><textarea id="review-reason" formControlName="reason" rows="4" maxlength="1000" style="resize: none" aria-describedby="review-reason-help"></textarea></app-field><div class="actions"><button type="button" class="secondary" autofocus (click)="close()" [disabled]="state.busy()">Cancel</button><button [disabled]="state.busy()">Finalize grade</button></div>@if(selected()){<app-status [state]="state"/>}</form></dialog>`})
export class ReviewComponent implements OnChanges {
  readonly api=inject(Api);readonly state=new ActionState();@Input() classroomId='';readonly grades=signal<Evaluation[]>([]);readonly selected=signal<Evaluation|null>(null);@ViewChild('dialog') dialog?:ElementRef<HTMLDialogElement>;
  readonly form=new FormGroup({reason:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.maxLength(1000),Validators.pattern(/\S/)]})});
  ngOnChanges():void{this.grades.set([]);this.load();}load():void{if(!this.classroomId)return;void this.state.run(async()=>this.grades.set(await this.api.evaluations(this.classroomId)));}
  review(grade:Evaluation):void{this.selected.set(grade);this.form.reset();this.dialog?.nativeElement.showModal();}close():void{this.form.reset();this.selected.set(null);this.dialog?.nativeElement.close();}
  finalize():void{if(!this.state.validate(this.form))return;void this.state.run(async()=>{await this.api.request('grading',`/evaluations/${this.selected()?.id}/finalize`,'POST',{reason:this.form.controls.reason.value,overrides:{}});this.close();this.grades.set(await this.api.evaluations(this.classroomId));},'Grade finalized. Performance will update after event processing.');}
}



