"""Actual gateway, PostgreSQL, object storage, Kafka and authorization integration.

Creates uniquely named test data; never drops databases or deletes user data.
Requires the local Compose stack, .env and httpx. Assertions are never mocked.
"""
import json
import subprocess
import time
from pathlib import Path
from uuid import uuid4

import httpx
from jsonschema import Draft202012Validator, FormatChecker

ROOT = Path(__file__).resolve().parents[1]
ENV = dict(line.split("=", 1) for line in (ROOT / ".env").read_text().splitlines() if line and not line.startswith("#"))
BASE = "http://localhost:8000/api"


def docker(*args: str, input: str | None = None, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["docker", "compose", *args], cwd=ROOT, input=input, text=True, capture_output=True, check=check, timeout=90)


def login(username: str, password_key: str) -> httpx.Client:
    res = httpx.post("http://localhost:8081/realms/learning/protocol/openid-connect/token", data={"client_id": "learning-e2e", "grant_type": "password", "username": username, "password": ENV[password_key]}, timeout=15)
    assert res.status_code == 200, f"Local identity login failed: {res.status_code}"
    return httpx.Client(base_url=BASE, headers={"Authorization": "Bearer " + res.json()["access_token"]}, timeout=25)


def request(client: httpx.Client, method: str, path: str, status: int = 200, **kwargs: object):
    response = client.request(method, path, **kwargs)
    assert response.status_code == status, f"{method} {path}: expected {status}, got {response.status_code}: {response.text[:400]}"
    data = response.json() if response.content else None
    if data is not None:
        import re
        service, _, resource = path.lstrip("/").partition("/")
        contract = json.loads((ROOT / f"contracts/http/{service}.openapi.json").read_text())
        route = "/v1/" + resource.split("?")[0]
        for template, methods in contract["paths"].items():
            if re.fullmatch(re.sub(r"\{[^}]+\}", "[^/]+", template), route) and method.lower() in methods:
                schema = methods[method.lower()]["responses"].get(str(status), {}).get("content", {}).get("application/json", {}).get("schema")
                if schema:
                    resolved = {**schema, "components": contract.get("components", {})}
                    Draft202012Validator(resolved, format_checker=FormatChecker()).validate(data)
                break
    return data


def eventually(action, predicate, label: str):
    deadline = time.monotonic() + 60
    while time.monotonic() < deadline:
        value = action()
        if predicate(value):
            return value
        time.sleep(1)
    raise AssertionError(f"Timed out: {label}")


def replay(service: str, topic: str, resource: str, fresh_id: bool = False) -> str:
    # resource is a UUID generated by this test or returned by a verified API.
    from uuid import UUID
    resource = str(UUID(resource))
    row = docker("exec", "-T", "postgres", "psql", "-U", service, "-d", service, "-At", "-c", f"SELECT body FROM outbox WHERE partition_key='{resource}' AND topic='{topic}'").stdout.strip()
    event = json.loads(row)
    schema = json.loads((ROOT / f"contracts/events/{topic}.schema.json").read_text())
    Draft202012Validator(schema, format_checker=FormatChecker()).validate(event)
    if fresh_id:
        event["event_id"] = str(uuid4())
    docker("exec", "-T", "kafka", "/opt/kafka/bin/kafka-console-producer.sh", "--bootstrap-server", "kafka:9092", "--topic", topic, input=json.dumps(event)+"\n")
    return event["event_id"]


def main() -> None:
    teacher = login("teacher", "TEACHER_PASSWORD")
    student = login("student", "STUDENT_PASSWORD")
    other = login("other-teacher", "OTHER_TEACHER_PASSWORD")
    teacher_profile = request(teacher, "POST", "/identity/me", json={})
    student_profile = request(student, "POST", "/identity/me", json={})
    request(other, "POST", "/identity/me", json={})
    assert httpx.get(BASE+"/identity/classrooms").status_code == 401
    room = request(teacher, "POST", "/identity/classrooms", 201, json={"name": "Integration " + str(uuid4())[:8]})
    request(student, "POST", "/identity/classrooms", 403, json={"name": "Forbidden"})
    request(other, "GET", f"/identity/classrooms/{room['id']}/access", 403)
    request(teacher, "POST", f"/identity/classrooms/{room['id']}/enrollments", json={"student_id": student_profile["id"]})
    skill = request(teacher, "POST", "/curriculum/nodes", 201, json={"kind": "skill", "name": "Integration exact decimals", "parent_id": None})
    doc = request(teacher, "POST", f"/content/documents?classroom_id={room['id']}&title=Integration", 201, content=b"A fraction is a part of a whole.", headers={"Content-Type": "text/plain"})
    assert doc["status"] == "extracted" and doc["chunks"][0]["text"] == "A fraction is a part of a whole."
    request(other, "GET", f"/content/documents/{doc['id']}", 403)
    request(student, "GET", f"/content/documents/{doc['id']}")
    original = student.get(f"/content/documents/{doc['id']}/original")
    assert original.status_code == 200 and original.content == b"A fraction is a part of a whole."
    pdf = request(teacher, "POST", f"/content/documents?classroom_id={room['id']}&title=PDF", 201, content=b"%PDF-1.7\n", headers={"Content-Type": "application/pdf"})
    assert pdf["status"] == "extraction_unsupported"
    assessment = request(teacher, "POST", "/assessment/assessments", 201, json={"classroom_id": room["id"], "title": "Decimal test", "questions": [{"prompt": "0.1 + 0.2?", "type": "numerical", "answer": "0.3", "tolerance": "0", "options": [], "skill_id": skill["id"]}, {"prompt": "Which is a fraction?", "type": "multiple_choice", "answer": "1/2", "tolerance": "", "options": ["1/2", "word"], "skill_id": skill["id"]}]})
    public = request(student, "GET", f"/assessment/assessments/{assessment['id']}")
    assert all("answer" not in q and "tolerance" not in q for q in public["questions"])
    submission = request(student, "POST", f"/assessment/assessments/{assessment['id']}/submissions", 201, json={"answers": {assessment["questions"][0]["id"]: "0.30", assessment["questions"][1]["id"]: "word"}})
    request(student, "POST", f"/assessment/assessments/{assessment['id']}/submissions", 409, json={"answers": {assessment["questions"][0]["id"]: "0.30", assessment["questions"][1]["id"]: "word"}})
    grades = eventually(lambda: request(teacher, "GET", f"/grading/evaluations?classroom_id={room['id']}"), lambda rows: len(rows) == 1, "draft grading")
    grade = grades[0]
    assert grade["status"] == "draft" and sum(e["awarded"] for e in grade["evidence"]) == 1
    performance_path = f"/analytics/performance/{student_profile['id']}?classroom_id={room['id']}"
    assert request(teacher, "GET", performance_path)["skills"] == []
    request(student, "POST", f"/grading/evaluations/{grade['id']}/finalize", 403, json={"reason": "Forbidden", "overrides": {}})
    request(other, "POST", f"/grading/evaluations/{grade['id']}/finalize", 403, json={"reason": "Forbidden", "overrides": {}})
    request(teacher, "POST", f"/grading/evaluations/{grade['id']}/finalize", json={"reason": "Integration teacher review", "overrides": {}})
    request(teacher, "POST", f"/grading/evaluations/{grade['id']}/finalize", 409, json={"reason": "Duplicate", "overrides": {}})
    result = eventually(lambda: request(teacher, "GET", performance_path), lambda result: len(result["skills"]) == 1, "analytics consumption")
    assert result["skills"][0]["attempted"] == 2 and result["skills"][0]["correct"] == 1 and result["skills"][0]["observed_accuracy"] == 0.5
    assert result["skills"][0]["evidence_status"] == "insufficient_evidence"
    request(student, "GET", f"/analytics/performance/{teacher_profile['id']}?classroom_id={room['id']}", 403)
    request(other, "GET", performance_path, 403)
    docker("restart", "grading", "analytics")
    replay("assessment", "assessment.submitted.v1", submission["id"])
    replay("grading", "grading.finalized.v1", grade["id"])
    duplicate_id = replay("grading", "grading.finalized.v1", grade["id"], fresh_id=True)
    eventually(lambda: docker("exec", "-T", "postgres", "psql", "-U", "analytics", "-d", "analytics", "-At", "-c", f"SELECT count(*) FROM inbox WHERE event_id='{duplicate_id}'").stdout.strip(), lambda value: value == "1", "duplicate processing")
    assert request(teacher, "GET", performance_path)["skills"] == result["skills"]
    assert len(request(teacher, "GET", f"/grading/evaluations?classroom_id={room['id']}")) == 1
    isolation = docker("exec", "-T", "postgres", "psql", "-U", "identity", "-d", "grading", "-c", "SELECT 1", check=False)
    assert isolation.returncode != 0 and "permission denied" in isolation.stderr.lower()
    print("PASS: gateway auth, classroom isolation, curriculum, S3 upload/extraction, answer-key secrecy, submissions, draft grading, teacher finalization, Kafka analytics, consumer restart, duplicate event and business-key idempotency, student privacy, database isolation.")


if __name__ == "__main__":
    main()
